name: shap_shap
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.9.0  
  get: ^4.7.2  
  get_storage: ^2.1.1
  carousel_slider: ^5.1.1

  # Firebase
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  google_sign_in: ^7.1.1
  firebase_storage: ^13.0.0

  # UI
  flutter_svg: ^2.2.0
  awesome_dialog: ^3.2.1
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  art_sweetalert: ^0.0.5
  rive: ^0.13.20
  flutter_circular_progress_indicator: ^0.0.3
  cached_network_image: ^3.4.1
  flutter_cache_manager: ^3.4.1

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/new_images/
    - assets/images/sign_up.svg
    - assets/images/google.svg
    - assets/images/account.svg
    - assets/images/password.svg
    - assets/images/farmer2.svg
    - assets/animations/
    - assets/fonts/
