// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvQVyyqCfZ9UBFNWGhVL1GTDnfMdtNoI4',
    appId: '1:1041806689164:web:75b2d49a2bc7e0603d8ca9',
    messagingSenderId: '1041806689164',
    projectId: 'shap-c03ae',
    authDomain: 'shap-c03ae.firebaseapp.com',
    storageBucket: 'shap-c03ae.firebasestorage.app',
    measurementId: 'G-TG2ZV9QHDW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0JygeU3OQW_u7VQzyLb5b5vihqM8mrj4',
    appId: '1:1041806689164:android:4874987f194e38c93d8ca9',
    messagingSenderId: '1041806689164',
    projectId: 'shap-c03ae',
    storageBucket: 'shap-c03ae.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDhFeKotYGeKxmxfvj-1j0c_eFcBxO9BU',
    appId: '1:1041806689164:ios:88c801dd795470243d8ca9',
    messagingSenderId: '1041806689164',
    projectId: 'shap-c03ae',
    storageBucket: 'shap-c03ae.firebasestorage.app',
    iosBundleId: 'com.example.shapShap',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDhFeKotYGeKxmxfvj-1j0c_eFcBxO9BU',
    appId: '1:1041806689164:ios:88c801dd795470243d8ca9',
    messagingSenderId: '1041806689164',
    projectId: 'shap-c03ae',
    storageBucket: 'shap-c03ae.firebasestorage.app',
    iosBundleId: 'com.example.shapShap',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvQVyyqCfZ9UBFNWGhVL1GTDnfMdtNoI4',
    appId: '1:1041806689164:web:74e690f65ac91a343d8ca9',
    messagingSenderId: '1041806689164',
    projectId: 'shap-c03ae',
    authDomain: 'shap-c03ae.firebaseapp.com',
    storageBucket: 'shap-c03ae.firebasestorage.app',
    measurementId: 'G-6MW025RKKL',
  );
}
